---
    name: Release
    
    on:
      release:
        types: [published]
      workflow_dispatch:
    
    jobs:
      release_zip_file:
        name: Prepare release asset
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v4
    
          - name: Create zip
            run: |
              zip daikin_d3net.zip -r ./custom_components
          - name: Upload zip to release
            uses: svenstaro/upload-release-action@v1-release
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: ./daikin_d3net.zip
              asset_name: daikin_d3net.zip
              tag: ${{ github.ref }}
              overwrite: true